export const POST_NEW_TRANSACTION_REQUEST = "POST_NEW_TRANSACTION_REQUEST"
export const POST_NEW_TRANSACTION_SUCCESS = "POST_NEW_TRANSACTION_SUCCESS"
export const POST_NEW_TRANSACTION_FAILURE = "POST_NEW_TRANSACTION_FAILURE"

export const FETCH_TRANSACTION_REQUEST = "FETCH_TRANSACTION_REQUEST"
export const FETCH_TRANSACTION_SUCCESS = "FETCH_TRANSACTION_SUCCESS"
export const FETCH_TRANSACTION_FAILURE = "FETCH_TRANSACTION_FAILURE"
