export const SIGNUP_REQUEST = "SIGNUP_REQUEST"
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS"
export const SIGNUP_FAILURE = "SIGNUP_FAILURE"

export const LOGIN_REQUEST = "LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAILURE = "LOGIN_FAILURE"

export const POST_NEW_TRANSACTION_REQUEST = "POST_NEW_TRANSACTION_REQUEST"
export const POST_NEW_TRANSACTION_SUCCESS = "POST_NEW_TRANSACTION_SUCCESS"
export const POST_NEW_TRANSACTION_FAILURE = "POST_NEW_TRANSACTION_FAILURE"

export const FETCH_TRANSACTION_REQUEST = "FETCH_TRANSACTION_REQUEST"
export const FETCH_TRANSACTION_SUCCESS = "FETCH_TRANSACTION_SUCCESS"
export const FETCH_TRANSACTION_FAILURE = "FETCH_TRANSACTION_FAILURE"